name: writer-cps-transformers
version: 0.1.1.3
synopsis: WriteT and RWST monad transformers
description:
  The WriterT and RWST monad transformers provided by writer-cps-transformers
  are written in continuation passing style and avoid the space-leak
  problem of the traditional Control.Monad.Trans.Writer.Strict and Control.Monad.Trans.Writer.Lazy.
  The corresponding MTL class instances are in the package writer-cps-mtl
  (<http://hackage.haskell.org/package/writer-cps-mtl>).
category: Control
author: Andy Gill, Ross Paterson, Daniel Mendler
maintainer: mail@daniel-mendler.de
copyright: 2016 Daniel Mendler
license: BSD3
github: minad/writer-cps-transformers

ghc-options:
- -Wall

dependencies:
- base < 6
- transformers >= 0.4 && < 0.6

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1,
  GHC == 8.2.1,
  GHC == 8.4.3,
  GHC == 8.6.1

library:
  source-dirs: src
